### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by SGSON** [SGSON/ASmallMuseum#24]
- [x] get Date
- [x] set categories
- [x] set menu form
- [x] set rating
- [x] get only 10 data at once
- [x] zoom-in and zoom-out
- [x] delete quick button
- [x] create review function
- [x] refresh
- [x] access Samsung gallery app
